finger:
  thumb:
    knuckle:
      position: -0.0315281 -0.0276566 -0.0024
      orientation: 1.5707963 0 2.5307278
      mesh: "ph_thumb.stl"

    proximal:
      mass: 0.0000000
      virtual_origin:
        position: 0.0000000 0.0000000 0.0000000
        orientation: 0 0 0
      real_origin:
        position: 0.0000000 0.0000000 0.0000000
        orientation: 0 0 0
      inertia:
        ixx: 0.0000000
        ixy: 0.0000000
        ixz: 0.0000000
        iyy: 0.0000000
        iyz: 0.0000000
        izz: 0.0000000
      inertia_origin:
        position:
          x: 0.0000000
          y: 0.0000000
          z: 0.0000000
        orientation:
          x: 0.0000000
          y: 0.0000000
          z: 0.0000000
      mesh: "ph_prossimal.stl"



  index:
    knuckle:
      mesh: "ph_index_knuckle.stl"


