right:

  finger:
    thumb:
      knuckle:
        position: -0.0315281 -0.0276566 -0.0024
        orientation: 1.5707963 0 2.5307278
        mesh: "ph_thumb.stl"
        mass: 3.2037862e-03
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
  
      proximal: &thumb_proximal
        mass: 3.2037862e-03
        virtual_origin:
          position: 16.5e-03 -4.2e-03 0
          orientation: -1.5707963 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
        mesh: "ph_proximal.stl"
      
      distal:
        mass: 3.2037862e-03
        virtual_origin:
          position: 16e-03 0 0
          orientation: 0 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
        mesh: "ph_distal.stl"
 

    index:
      knuckle:
        position: -20e-03 0 6.0267000e-03
        orientation: 0 0 1.7453293
        mesh: "ph_index_knuckle.stl"
        mass: 3.2037862e-03
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
      
      proximal:
        <<: *thumb_proximal
        virtual_origin:
          position: 15e-03 -3.7e-03 0
          orientation: 1.5707963 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0


    middle:
      knuckle:
        position: 0 0 6.3e-03
        orientation: 0 0 1.5707963
        mesh: "ph_middle_knuckle.stl"
        mass: 3.2037862e-03
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0

      proximal:
        mass: 3.2037862e-03
        virtual_origin:
          position: 15e-03 0 -0.273297e-03
          orientation: 1.5707963 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
        mesh: "ph_proximal_middle.stl"


    ring: 
      knuckle: &ring_knuckle
        position: 20e-03 0 6.02670e-03
        orientation: 0 0 1.3962638
        mesh: "ph_ring_knuckle.stl"
        mass: 3.2037862e-03
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0

      proximal:
        <<: *thumb_proximal
        virtual_origin:
          position: 15e-03 3.7e-03 0
          orientation: 1.5707963 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0
    
    little:
      knuckle:
        <<: *ring_knuckle
        position: 37e-03 -5e-03 6.02670e-03
        orientation: 0 0 1.3089971
  
      proximal:
        mass: 3.2037862e-03
        virtual_origin:
          position: 15e-03 3.7e-03 0
          orientation: 1.5707963 0 0
        real_origin:
          position: 9e-03 0 0
          orientation: 0 0 0
        inertia:
          ixx: 6.5745301e-08
          ixy: -3.1362083e-10
          ixz: 3.5152512e-08
          iyy: 2.2281085e-07
          iyz: -5.2782785e-11
          izz: 2.0956023e-07
        inertia_origin: 
          position: 1.6018749e-3 1.9731832e-04 -1.8504085e-03
          orientation: 0 0 0
        mesh: "ph_prossimal_little.stl"




left:
